extends Object

const Base = preload("./base.gd")
const FancyWideStreetLight = preload("./fancy-wide-street-light.gd")
const FancyStreetLight = preload("./fancy-street-light.gd")
const StreetLight = preload("./street-light.gd")
const StreetClock = preload("./street-clock.gd")
const BannerPost = preload("./banner-post.gd")
const WhiteFenceEntrance = preload("./white-fence-entrance.gd")
const BigWoodEntrance = preload("./big-wood-entrance.gd")
const WoodEntrance = preload("./wood-entrance.gd")
const GrassEntrance = preload("./grass-entrance.gd")
const GrassRing = preload("./grass-ring.gd")
const RoundFountainPool = preload("./round-fountain-pool.gd")
const BigSquareFountainPool = preload("./big-square-fountain-pool.gd")
const StandaloneFountain = preload("./standalone-fountain.gd")
const WallFountain = preload("./wall-fountain.gd")
const SmallFlowerBed = preload("./small-flower-bed.gd")
