extends Object

const Barn = preload("./barn.gd")
const House = preload("./house.gd")
const Crop = preload("./crop.gd")
const FruitTree = preload("./fruit-trees.gd")
const FoodIcon = preload("./food-icon.gd")
const Silo = preload("./silo.gd")
const Waterer = preload("./waterer.gd")
const TreeStump = preload("./tree-stump.gd")
const BirdsNest = preload("./birds-nest.gd")
const Beehive = preload("./beehive.gd")
const BeehiveRack = preload("./beehive-rack.gd")
const StrawHeap = preload("./straw-heap.gd")
const StrawBundle = preload("./straw-bundle.gd")
const ButterChurner = preload("./butter-churner.gd")
const CheesePress = preload("./cheese-press.gd")
const Mixer = preload("./mixer.gd")
const WindBlade = preload("./wind-blade.gd")
const WindBladeSmall = preload("./wind-blade-small.gd")
const WaterWheel = preload("./water-wheel.gd")
const WaterWheelNS = preload("./water-wheel-ns.gd")
const WaterWheelHalf = preload("./water-wheel-half.gd")
