extends Object

const Base = preload("./base.gd")
const KitchenWideDesk = preload("./kitchen-wide-desk.gd")
const KitchenDesk = preload("./kitchen-desk.gd")
const KitchenSink = preload("./kitchen-sink.gd")
const KitchenStove = preload("./kitchen-stove.gd")
const KitchenShelvedDesk = preload("./kitchen-shelved-desk.gd")
const KitchenSidedWideDesk = preload("./kitchen-sided-wide-desk.gd")
const RoundTable = preload("./round-table.gd")
const Stool1 = preload("./stool-1.gd")
const Stool2 = preload("./stool-2.gd")
const TwinBed = preload("./twin-bed.gd")
const Chair = preload("./chair.gd")
const WideShelving = preload("./wide-shelving.gd")
const WideGondola = preload("./wide-gondola.gd")
